# Generated by Django 4.0.2 on 2022-02-15 06:32

from django.db import migrations, models
import uuid


def create_uuid(apps, schema_editor):
    chat = apps.get_model('form', 'Chat')
    for chat_item in chat.objects.all():
        chat_item.slug = uuid.uuid4()
        chat_item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='slug',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(create_uuid, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='chat',
            name='slug',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='chat',
            name='id',
        ),
    ]
